### ISSUE TITLE
Bundled Tomcat 9.0.x Does Not Continue Starting

### ISSUE THREAD

**Issue by Yahya-Allam** [redhat-developer/rsp-server-community#101]
I am trying to run the bundled Tomcat server which comes with Liferay DXP but once it logs  "Sidecar Elasticsearch liferay started at 127.0.0.1:9201" as appears in the attached snapshot the state of the server change suddenly from "starting" to "stopped" and does not continue.
![image](https://user-images.githubusercontent.com/76212827/134987107-4a68bd6f-6993-48c2-a988-c372e39f2ab0.png)

**Comment by LeoLozes** [comment]
It was because of the automatic server timeout. It can be tweaked in the "Edit Server" configuration, adding your custom timeout:

`"server.timeout.startup": "500000"`

**Comment by robstryker** [comment]
Sorry I mised this issue. @LeoLozes  is correct. You can adjust the timeouts by editing the server file.
