### ISSUE TITLE
Web application auto update

### ISSUE THREAD

**Issue by bibhas2** [redhat-developer/rsp-server-community#106]
This is a feature request. We need the ability to automatically deploy to Tomcat when code base changes. The current functionality is rather limited and not usable for a real life project. I find myself constantly having to rebuild and restart the Tomcat server. Are there any plans to make Tomcat based coding more seamless? Thanks.

**Comment by robstryker** [comment]
I know your issue was here first but this other issue has a bit more engagement, so closing yours to solidify discussion on the other. 

https://github.com/redhat-developer/rsp-server-community/issues/137
