### ISSUE TITLE
How do I use this extension, where is the getting started ?! 

### ISSUE THREAD

**Issue by belaad** [redhat-developer/rsp-server-community#112]
I see 
```
# Now build the extension
cd vscode/

#Build this extension's code
npm install
npm run build
npm run test
vsce package
```
what is this "cd vscode", where is that on a Mac? how do I connect my project to this? I have a project that builds into a war file. How do I use this extension?

**Comment by jeffmaury** [comment]
This is for developers that want to provide new features to the extension.
As a user, you need to install:

- https://marketplace.visualstudio.com/items?itemName=redhat.vscode-rsp-ui
- https://marketplace.visualstudio.com/items?itemName=redhat.vscode-community-server-connector (for Tomcat,...)
- https://marketplace.visualstudio.com/items?itemName=redhat.vscode-server-connector (for Wildfly/EAP)

**Comment by robstryker** [comment]
As @jeffmaury  said, it's best to install this from the market place unless you are looking to make changes or fix bugs to the extension itself. The links @jeffmaury  has provided also show how to use it. If you have any other more specific questions, feel free to re-open this issue.
