### ISSUE TITLE
Unable to create the server: Extension backend error - failed to download runtime in time

### ISSUE THREAD

**Issue by Joohangooi** [redhat-developer/rsp-server-community#115]
I'm getting this error message when I trying to download/link a local glassfissh or what ever server. I'm currently using MacBook  M1, why will this happen? I had tried with windows but it is doing well, so it seems like the problem only happen on my Mac

**Comment by jabreland** [comment]
I am also having this issue running it on VS Code on an up to date Fedora 35 Desktop x86/64.

**Comment by robstryker** [comment]
Looking into it. It might be related to java 17. Trying to get a release out which I think will fix it.

**Comment by Joohangooi** [comment]
Yeah I had downgraded my java version from JDK 17 to JDK 11 and it works! Thanks !
