### ISSUE TITLE
Is there a way to launch/debug a server with a launch.json configuration?

### ISSUE THREAD

**Issue by Foxhunter981** [redhat-developer/rsp-server-community#126]
Hi all,

I really like this extension, and I've been using it to launch my Java EE project via Tomcat, but I'm running into an issue where the watch panel is unable to parse variables I ask it to saying the "project could not be parsed and to specify it in launch.json" or something like that. I've seen forum posts talking about this issue going nowhere and I was curious what would happen if I were to be able to launch a community server via a launch. Son config where I can explicitly state the "project" name. Thoughts?

**Comment by robstryker** [comment]
I've been unable to figure out what's causing the "project could not be parsed" launch.json issue. In theory absolutely none of RSP or any projects you want to deploy to a server should require a launch.json or anything like it.

**Comment by robstryker** [comment]
To answer your question more directly, I can't imagine any way that RSP would be able to launch a server via a launch.json file. I beleive that file simply isn't suited to the work we do to launch an RSP and an associated runtime (tomcat, wildfly, etc) and then deploy the project. 

https://github.com/redhat-developer/rsp-server-community/issues/85#issuecomment-1121328660  is the issue for the launch.json problem
