### ISSUE TITLE
Cannot start a local Tomcat server -- getting "Unable to start the RSP server"

### ISSUE THREAD

**Issue by halloleo** [redhat-developer/rsp-server-community#134]
In VS Code I have created a Maven project for a Java Servlet, compiled it and now I try to deploy the generated `.war` file to a local Tomcat 8.5 via the Community Server Connectors extension.

However when the extension loads I always get an error balloon with the message:

> Unable to start the RSP server:  Extension backend error - rsp error - community server connector failed to start - typeerror: cannot read properties of undefined (reading 'map')

Any idea why this happens and how I can fix this?

***
### Note

I file this issue, because this _might_ be a problem with the extension itself.  -- In case there's _no_ issue with the extension, but it is rather some configuration problem, I have asked a [similar question on StackOverflow][2].

[2]: https://stackoverflow.com/questions/72960450/cannot-start-a-tomcat-server-with-the-community-server-connectors-extension-in-v
[1]: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-community-server-connector

**Comment by halloleo** [comment]
I had used Java 8 as the JDK. Now I use for VS Code a Java 17 JDK -- and it works!

**Comment by robstryker** [comment]
Good to hear the issue is resolved!

**Comment by jcrben** [comment]
This should use the embedded JRE from vscode-java and require the user to set it - maybe I got screwed up somehow but I had to set it with `"rsp-ui.rsp.java.home": "C:/Users/bncrsy/.vscode/extensions/redhat.java-1.13.0-win32-x64/jre/17.0.5-win32-x86_64",`

**Comment by robstryker** [comment]
In the past we used the jre from vscode-java but we switched it because we realized trying to ensure our RSP used the same java as the LSP might introduce issues if for example we upgrade the RSP to a newer java before the vscode-java extension does.  But we still should be defaulting to the vscode-java entry if a user hadn't set an rsp-java and also hadn't set a custom vm for the given tomcat server as well.

**Comment by jcrben** [comment]
@robstryker thanks for the clarification - while it might seem like excessive detail I think surfacing something like this in a docs page could be helpful
