### ISSUE TITLE
mapProperty.launch.env not working with tomcat tomcat 8.5 windows 10

### ISSUE THREAD

**Issue by ghost** [redhat-developer/rsp-server-community#135]
I am trying to set an environment var for tomcat 8.5 the server json saves without error but the variable does not appear to be set when the server starts.
Vscode details
Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19042
Extension: [Community Server Connectors v0.25.4]
Tomcat Version: [Apache Tomcat/8.5.63]
OS Name: [Windows 10]
OS Version: [10.0]
OS Architecture: [amd64]
JVM Version: [1.8.0_332-b08]
JVM Vendor: [Amazon.com Inc.]

server.json
```{
  "args.override.boolean": "true",
  "args.program.override.string": "start",
  "args.vm.override.string": "-Djava.util.logging.config.file=c:/Work/www/tomcat8.5/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dcatalina.base=c:/Work/www/tomcat8.5 -Dcatalina.home=c:/Work/www/tomcat8.5 -Djava.io.tmpdir=c:/Work/www/tomcat8.5/temp -Dsolr.clustering.enabled=true -Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8 -agentlib:jdwp=transport=dt_socket,server=y,address=8880,suspend=n -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8890 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false",
  "id": "Tomcat 8.5",
  "id-set": "true",
  "mapProperty.launch.env": {
    "LUCEE_MAPPING_FIRST": "true"
  },
  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.server.tomcat.85",
  "server.base.dir": "c:/Work/www/tomcat8.5",
  "server.deploy.dir": "${server.base.dir}/webapps/",
  "server.home.dir": "c:/Work/www/tomcat8.5",
  "server.http.port": "5506"
}
```
LUCEE_MAPPING_FIRST is not visible to tomcat, I can set system properties successfully in the args.vm.override.string
any guidance would be much appreciated
Dave

**Comment by robstryker** [comment]
Sorry for this error. This was recently fixed here: 

https://github.com/redhat-developer/rsp-server/commit/798b8accc6c119e8093712b492eee6653453cfe4

It will make it into the next release.
