### ISSUE TITLE
Why the extension is always on "Starting"?

### ISSUE THREAD

**Issue by EichnerXu** [redhat-developer/rsp-server-community#138]
Through some videos and blogs，i guess the extension should switch to the "Started".But it seems that i stuck in "Starting".
is there anybody meet the same thing?

**Comment by robstryker** [comment]
I'm a bit confused. Do you mean the 'extension' is stuck on starting? Or your application server (tomcat, wildfly, etc) is stuck on starting? Some clarification here might help me narrow down the possibilities.

**Comment by EichnerXu** [comment]
> I'm a bit confused. Do you mean the 'extension' is stuck on starting? Or your application server (tomcat, wildfly, etc) is stuck on starting? Some clarification here might help me narrow down the possibilities.

the extension is stuck on starting. there wasn't a button to create a server.

**Comment by robstryker** [comment]
Can you please include a screenshot of this? I'm not sure if you mean the extension itself or one of the RPSs in the servers view, or one of the servers. I think you've clearly said it's not a server itself but maybe the RSP is refusing to start? Thanks.

**Comment by robstryker** [comment]
Closing old issue; unable to replicate
