### ISSUE TITLE
Unable to start local Tomcat 10.0.18

### ISSUE THREAD

**Issue by gckuan-kossan** [redhat-developer/rsp-server-community#139]
Greetings!

I unable to start local server, the output pane show:

> Error: Could not find or load main class Software
> Caused by: java.lang.ClassNotFoundException: Software

This is the application and version
- VSCode v1.71.0
- Community Server Connectors extensions v0.25.6
- Tomcat v10.0.18
- Amazon Corretto 18

thanks for helping!

sorry, i'm newbie on this...

**Comment by gckuan-kossan** [comment]
erm... it's still functioning, just not able to start or stop by this extension, but able to deploy and remove the development war file, it just need to click full "full pulish"

**Comment by robstryker** [comment]
hi... curious, does it work if you use a different jdk / jre?  oracle or openjdk?

**Comment by gckuan-kossan** [comment]
> hi... curious, does it work if you use a different jdk / jre? oracle or openjdk?

Hi, I'm using amazon corretto 18. it's working, just unable to 'start/stop' server thru this extension.

**Comment by robstryker** [comment]
While your issue was unclear, I think you likely had a tomcat path that included spaces? If so, this issue is likely fixed by the following commit:

commit b0e0d07c81923fae8e39585dacea81e01bc9de60 (contrib1/master)
Author: Rob Stryker <rob@oxbeef.net>
Date:   Thu Nov 3 15:44:40 2022 -0400

    Add single quotes to allow paths with spaces

**Comment by robstryker** [comment]
Closing old issue;  if issue persists in newer releases, please re-open.
