### ISSUE TITLE
Error when using server path with spaces

### ISSUE THREAD

**Issue by jeffrpowell** [redhat-developer/rsp-server-community#148]
I happen to be using Tomcat 8.5.x. Not sure if this issue is also present for other servers.

1. Add a new server, choose to add from disk (i.e. not downloaded)
2. Select a tomcat installation folder that has spaces in its absolute path
    * Set the default CATALINA_HOME for the server
3. Try to start the server (without any deployments)

You'll get an error mentioning the part of your path that has spaces.
For example, I had a server located at C:\Program Files\Apache Software\tomcat-8.5.83, and I was getting an error saying ClassNotFoundException at Files\Apache

**Comment by robstryker** [comment]
* b0e0d07 - (HEAD -> master, origin/master) Add single quotes to allow paths with spaces (5 weeks ago) <Rob Stryker>

This was fixed but not yet released
