### ISSUE TITLE
Focus steal on sync

### ISSUE THREAD

**Issue by Mistra** [redhat-developer/rsp-server-community#149]
Hello and thank you for the extension, I'm testing it out.

I found out this issue while running a .war compiled from a maven project on Tomcat (8.5) in debug mode.
After a "mvn clean package" the extension (listening to tomcat) finds out it's out of sync and attempts republish, which is fine.
The not fine part is that for each and every change of state the extension withstands, it steals the focus from the current code document. After a while this becomes quite annoying.
Is this a bug or a feature? In any case, is there a way to mitigate or avoid this behavior?

Thank you

**Comment by robstryker** [comment]
It depends on exactly what's happening, to be honest. 

If your workspace is republishing and then the server is recognizing the redeployment and putting output to the console, and THAT is what's stealing the focus, then yes, we have a way to override this behavior. 

![image](https://user-images.githubusercontent.com/630383/206008517-eda8b03c-9da8-4e97-ae68-3b138e36400a.png)

You can mark the console not to steal focus on server output. 

Please close this issue if this answer is sufficient for you.

**Comment by robstryker** [comment]
Closing old issue as reporter did not respond.
