### ISSUE TITLE
Popup does not appear correctly when JDK is not installed.

### ISSUE THREAD

**Issue by shblue21** [redhat-developer/rsp-server-community#152]
Hello! 
When i extension is executed without JDK setting, an unknown message occurs as shown below.  

> Unable to start the RSP server: Extension backend error 
> rsp error - community server connector failed to start - 
> typeerror: cannot read properties of undefined (reading 'map')

<img src="https://user-images.githubusercontent.com/25363091/210214131-df86a52d-1424-49d2-8b5a-609e8d4ba627.png" width=50% height=50%>  

When I checked, `error.btns` value was missing from reject in the `resolveRequirements` function.  

``` js
// server.ts 33 line
vscode.window.showErrorMessage(error.message, ...error.btns.map(btn => btn.label))

```
<img src="https://user-images.githubusercontent.com/25363091/210214527-88338526-d39f-42fb-a2e4-dec9a720f2ea.png" width=50% height=50%>

**Comment by robstryker** [comment]
Good catch, working on it and parallel fix for vscode-server-connector repo.

**Comment by shblue21** [comment]
@robstryker Thanks for merging!
