### ISSUE TITLE
Starting Tomcat Server 9.xx resuls in .FileNotFoundException for conf\logging.properties

### ISSUE THREAD

**Issue by bigtfromaz** [redhat-developer/rsp-server-community#174]
I can't find anything online regarding this error so I'm reporting an issue here.  

Steps to reproduce. 

- Install Server Connector
- Create a Tomcat 9.0.45 server. Select download, or use existing. It does not matter
- Start the server and receive the following error

`Configuration error
java.io.FileNotFoundException: 'd:\Tomcat\apache-tomcat-9.0.45\conf\logging.properties' (The filename, directory name, or volume label syntax is incorrect)`

Note that d:\Tomcat\apache-tomcat-9.0.45\conf\logging.properties exists.

Configuration

- Windows 11 Pro Version 22H2
- VSCODE is up to date at this time, Version 1.76.0
- Language support for Java Version 1.15.0
- Server Connector - v0.26.1
- Remote Server Protocol UI - v0.23.17
- All Marketplace Extensions are up to date

I see these extensions are preview. This issue is keeping me from debugging, and I am on a deadline. I also see the Tomcat for Java extension is deprecated. Is there no stable integration available for Tomcat at this time?

Any guidance you might provide will be greatly appreciated. In the meantime, I will see if I can make Tomcat for Java work.

**Comment by s850042002** [comment]
Same issue. Here's my environment.
- Windows 10 21H2 19044.2604
- VSCODE 1.76.0
- Tomcat 9.0.55
- Language support for Java Version 1.15.0
- Server Connector - v0.26.3
- Remote Server Protocol UI - v0.23.17

**Comment by s850042002** [comment]
To anyone encounter this issue, you can install the previous version as workaround.
![image](https://user-images.githubusercontent.com/4788733/223045329-54ed28c2-a8c7-48b7-a565-bdf5dbefcf6d.png)

**Comment by luca2707** [comment]
I am having the same issue with Community Server Connectors v0.26.3 on Windows 11, Tomcat 9.0.71, VSCode 1.76.0.
Reverting to the previous version v0.25.7 worked for me.

**Comment by victj99** [comment]
Same here but with Tomcat 7, i set rsp-ui.rsp.java.home to jdk 11 path (by a warning) and then tomcat not start.

- Windows 10 22H2
- Vscode 1.76.0

**Comment by InTEGr8or** [comment]
I set rsp-ui.rsp.java.home to jdk 11 because of the Community Server connector also. When you revert Community Server Connector back to 0.25.7 you also have to revert rsp-ui.rsp.java.home to the JDK for you code, I think.

**Comment by robstryker** [comment]
I just dug in deep and it seems the only difference I can find of any signficance between the command my tools are launching, and the command a catalina.sh script would run, is the use of single quotes vs double quotes to keep a path (like catalina.base or catalina.home or the tmpdir) as a single parameter. 

I'm actually very very surprised by this.

**Comment by robstryker** [comment]
Workaround exists:

Right-click your server, edit server. You will see a JSON file appear. 

Set the 'args.override.boolean' property to true. 
Then, in the 'args.vm.override.string' property, replace all single quotes with **\"**

The servers should then start fine.

**Comment by krishna-vasudev** [comment]
After this fix ,everything seems to work fine on windows.

**Comment by bigtfromaz** [comment]
In the interest of time, I had switched back to Tomcat for Java and it still works fine for my use case. If you choose to leave this open and close it after the fix is deployed, I'll be happy to retest.

Thanks for the responses.

**Comment by robstryker** [comment]
@bigtfromaz  The fix has been deployed and I've manually tested that it appears to work. @krishna-vasudev  seems to verify it works as expected. 

I'm really sorry for this issue cropping up at all. I recognize that even a day of downtime in a critical devtool is an issue. This really boils down to a few issues on my end and insufficient testing on both major OS's. 

I'll be closing the issue now as it appears to be fixed.

**Comment by bigtfromaz** [comment]
Tomcat 9 now runs correctly in my configuration, managed by Community Server Connectors version 0.26.4 

Thanks for your help.
