### ISSUE TITLE
It seems that the server cannot be deleted.

### ISSUE THREAD

**Issue by coderpyh** [redhat-developer/rsp-server-community#177]
There are only "Create New Server". I didn't find something like "delete server".

**Comment by coderpyh** [comment]
I find the way. Ctrl+Shift+P, "Servers: Remove Server". Or directly delete the file in "~\.rsp\redhat-community-server-connector\servers\". I suggest adding this function to the right click menu.

**Comment by robstryker** [comment]
I'm a bit confused what your UI looked like.   This is what it looks like for me, typically:

![image](https://user-images.githubusercontent.com/630383/227302119-6c75dd97-a2ac-4a85-bf88-26fb14a50954.png)

**Comment by coderpyh** [comment]
Oh, thanks! I find it. Maybe I took wrong operations before.
