### ISSUE TITLE
Java version checking fails

### ISSUE THREAD

**Issue by akuusik-perforce** [redhat-developer/rsp-server-community#185]
An error pop-up notification "Error getting java version for <path>: 'java -version' output was unable to be parsed." is shown at extension startup. It does not happen consistently though.
Closer investigation (debugging) revealed that the issue happens due to a race condition in checkJavaVersion function in requirements.ts. cp.execFile() callback is executed **after** process.on('exit') callback in the problem situation. According to child_process [documentation](https://nodejs.org/api/child_process.html#class-childprocess), this can be considered as expected behavior:

> When the 'exit' event is triggered, child process stdio streams might still be open.

**Comment by robstryker** [comment]
Thanks for this report. This is likely the bug we've been trying to track down.
