### ISSUE TITLE
Publish to open-vsx registry

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/rsp-server-community#188]
Publish the latest version of extension on open-vsx registry to be used across VSCodium, OpenShift DevSpaces.

**Comment by mohitsuman** [comment]
@robstryker please link to the open-vsx registry extension URL.

**Comment by rgrunber** [comment]
I see https://open-vsx.org/extension/redhat/vscode-rsp-ui , https://open-vsx.org/extension/redhat/vscode-server-connector but not the rsp-server-community extension.

Also FWIW, the metadata is searchable as https://open-vsx.org/api/${publisher}/${name} (eg. https://open-vsx.org/api/redhat/vscode-server-connector)

**Comment by mohitsuman** [comment]
The extension is now published on open-vsx https://open-vsx.org/extension/redhat/vscode-community-server-connector.
