### ISSUE TITLE
Example to set classpath as in setEnv.sh

### ISSUE THREAD

**Issue by vignesh-irtt** [redhat-developer/rsp-server-community#193]
Need an example on how to set CLASSPATH as we usually set on setEnv.sh.
Need to add some jar paths to the CLASSPATH so that my webapp can be deployed.
Feel free query more from me.
Anybody please help me.

**Comment by robstryker** [comment]
We do not currently have a way to override the classpath. The classpath is set in the definition for the server type. Here is an example:   https://github.com/redhat-developer/rsp-server-community/blob/master/rsp/runtimes/bundles/org.jboss.tools.rsp.server.tomcat/src/main/resources/servers.json#LL306C12-L307C1

I will look into seeing if this is doable asap.

**Comment by robstryker** [comment]
Seems it's doable to allow arbitrary jars be added to the classpath so long as those jars live underneath the tomcat home directory. I should be able to execute a quick patch for this. 

However, to allow for absolute paths outside of the tomcat directory to be added to the classpath, I'd need to fix an upstream bug in https://github.com/redhat-developer/rsp-server

**Comment by vignesh-irtt** [comment]
Thank you for your reply and taking into account.
I tried setting classpath env variable in *mapProperty.launch.env *but it
didn't work.
For now I'm putting jars into tomcat lib folder.

**Comment by robstryker** [comment]
This is partially completed, with relative paths only, which isn't terribly useful for you. Watch https://github.com/redhat-developer/rsp-server/issues/703  to allow the ability to add absolute paths when possible. 

Leaving this issue open so I remember to document.

**Comment by robstryker** [comment]
Once fully released, a user will be able to edit their representation of their server by right-clicking on their server in the `Servers` view and selecting the `Edit Server` menu item. Once the server's json definition loads up, a user should be able to add something like the following line to their server definition:

```
  "server.classpath.additions": "/home/rob/tmp/example-api.jar;/home/rob/tmp/other.jar",
```

By storing this property in the server json file, this value will be used to resolve the server-type's definition's classpath that is used to start the server. For tomcat, for example, the line `"classpath": "bin/bootstrap.jar;bin/tomcat-juli.jar"` has been replaced with `"classpath": "bin/bootstrap.jar;bin/tomcat-juli.jar;${server.classpath.additions}"`

This means the value from the server json will be pulled in and added on to the end of the server-type's hard-coded classpath. 

Hopefully this helps and documents how to use this feature, once fully released.

**Comment by vignesh-irtt** [comment]
Seems clear to me and what I need exactly

**Comment by robstryker** [comment]
This has been released

**Comment by vignesh-irtt** [comment]
Thanks a lot.
