### ISSUE TITLE
Add jbang script to add new Websphere Liberty easily

### ISSUE THREAD

**Issue by robstryker** [redhat-developer/rsp-server-community#201]
* c03f7f2 - Run jbang script for Liberty (4 hours ago) <Rob Stryker>
* d3d10d7 - Add jbang for Liberty, restructure server definition file (4 hours ago) <Rob Stryker>

**Comment by alainrobert** [comment]
this is awesome, when is the next release ?

**Comment by robstryker** [comment]
The jbang script is on my side, to simplify adding new adapters and releasing them. 

It won't be available on the client side. But it will allow me to run the script once a day and see if anything has changed and maybe make snap releases.

**Comment by alainrobert** [comment]
I see thanks. I thought it would generate a full list for liberty as there is for tomcat. I  am hoping to see an update of the extension with a liberty more recent than 21.0

**Comment by robstryker** [comment]
![image](https://github.com/redhat-developer/rsp-server-community/assets/630383/e474a0af-f367-47e0-946e-6a43309b0578)

Released ;)
