### ISSUE TITLE
How to stop a specific domain from Glassfish within Community Server Connection VSCODE extension

### ISSUE THREAD

**Issue by JLLMNCHR** [redhat-developer/rsp-server-community#207]
Working with **VSCode** and **GlassFish 5** via the **Community Server Connector** extension, I am trying to work with my own domain (_sfeaapp_), instead of the default domain (_domain1_).

To this goal, from a **terminal** I have successfully created my '_sfeaapp_' domain, with the `asadmin create-domain sfeaapp` command.

Also, from VSCode I have been able to customize the start, thanks to editing 2 lines in the JSON that appears when '**Edit Server**' is clicked, so that it starts gentently on my '_sfeaapp_' domain when I click the '**Start Server**' action:

```
   "args.override.boolean": "true",
   "args.program.override.string": "start-domain --verbose sfeaapp",
```

But, the problem is that, when I try to stop the server, with '**Stop Server**' option, I get the following message and it doesn't know which domain to stop:

> The domains directory C:\Installed\glassfish5.0.1\glassfish\domains
> contains multiple domains. Please specify a domain.
> Available domains: domain1, sfeaapp
> Command stop-domain failed.
> Any help will be appreciatted.

**Comment by robstryker** [comment]
This has been released. Specifically, you are now allowed to override stop arguments. 

It's possible that the better solution should have been to pass the domain name into stop args by default. But I've already made a release and... didn't think of that.
