### ISSUE TITLE
How to prevent sidebar popup when server status changes?

### ISSUE THREAD

**Issue by hoywu** [redhat-developer/rsp-server-community#211]
I use Deploy plugin to automatically publish changes every time I save a code file.
However, any changes to the files in the Deployment directory will cause the sidebar pop up.

(Notice that the status of Tomcat Server changes to "Publish Required", and then changes back to "Synchronized")
![2023-11-14-20-46-59](https://github.com/redhat-developer/rsp-server-community/assets/100393533/ab7f7b76-cf0c-49ca-99c9-0e12561e47be)

I can't find a configuration option that can disables this behavior.
Is there any solution for this?

Any suggestions are greatly appreciated. Thank you!

**Comment by robstryker** [comment]
Hrmm... I've never seen this behavior.  I'll... look into it.

**Comment by hoywu** [comment]
Thank you for looking into it!

**The steps to reproduce for your reference**

1. Create an empty workspace and open it in vscode (e.g., `/tmp/tmp`)
2. Create a Tomcat server in the Community Server Connectors plugin (with "server on disk")
3. Add a **Exploded** deployment on the Tomcat server, and select the current workspace directory (`/tmp/tmp`)
4. Create an empty html file in the workspace (e.g., `/tmp/tmp/index.html`)
5. Start Tomcat server, wait for the status to change to `(Started) (Synchronized)`
6. Open `/tmp/tmp/index.html` and collapse sidebar
7. Type any code in `/tmp/tmp/index.html` and save it
8. You will see the collapsed sidebar expand automatically

**Environment**

```
**VS Code**
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:50:47.800Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.6.1-arch1-1

redhat.vscode-community-server-connector: v0.26.14

**Tomcat**
Server version: Apache Tomcat/10.1.15-dev
Server built:   Oct 12 2023 04:39:11 UTC
Server number:  10.1.15.0
OS Name:        Linux
OS Version:     6.6.1-arch1-1
Architecture:   amd64
JVM Version:    21+35
JVM Vendor:     Oracle Corporation
```

**Server Config**

```
{
  "args.override.boolean": "false",
  "args.program.override.string": "start",
  "args.shutdown.program.override.string": "stop",
  "args.shutdown.vm.override.string": "-Djava.util.logging.config.file=\"/usr/share/tomcat10/conf/logging.properties\" -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dcatalina.base=\"/usr/share/tomcat10\" -Dcatalina.home=\"/usr/share/tomcat10\" -Djava.io.tmpdir=\"/usr/share/tomcat10/temp\"",
  "args.vm.override.string": "-Djava.util.logging.config.file=\"/usr/share/tomcat10/conf/logging.properties\" -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dcatalina.base=\"/usr/share/tomcat10\" -Dcatalina.home=\"/usr/share/tomcat10\" -Djava.io.tmpdir=\"/usr/share/tomcat10/temp\"",
  "id": "Tomcat 10.x",
  "id-set": "true",
  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.server.tomcat.100",
  "server.base.dir": "/usr/share/tomcat10",
  "server.classpath.additions": "",
  "server.deploy.dir": "${server.base.dir}/webapps/",
  "server.home.dir": "/usr/share/tomcat10",
  "server.http.host": "localhost",
  "server.http.port": "8080",
  "vm.install.path": "",
  "deployables": {
    "/tmp/tmp": {
      "label": "/tmp/tmp",
      "path": "/tmp/tmp",
      "options": {}
    }
  }
}
```
