### ISSUE TITLE
Payara 6.* can't be launched after download.

### ISSUE THREAD

**Issue by olegbal** [redhat-developer/rsp-server-community#218]
Any version of payara server 6.* can't be installed. 

License agreement is empty

<img width="611" alt="Screenshot 2024-02-07 at 04 02 23" src="https://github.com/redhat-developer/rsp-server-community/assets/11442033/77ae7a69-bdcd-4a7e-9227-79efa0002894">

And then after download i can see next error
![image](https://github.com/redhat-developer/rsp-server-community/assets/11442033/fe447af7-68ee-4ded-ac72-549b587a5246)

I tried payara **5**. And license agreement is fetched properly and server can be downloaded an launched as expected.

Can you please take a look what is wrong?

**Comment by robstryker** [comment]
I'm on it.
