### ISSUE TITLE
Tomcat server not stopping in vscode

### ISSUE THREAD

**Issue by DebanilRoy** [redhat-developer/rsp-server-community#226]
![Screenshot (22)](https://github.com/redhat-developer/rsp-server-community/assets/42070473/9e70f634-8b76-46cf-8c68-f5e9e2ec8728)
The server does not stop and is stuck on "(Stopping) (Synchronised)".

**Comment by robstryker** [comment]
I'm not currently able to replicate this. 

What precise version of tomcat are you using? Did you use the vscode tools to download the tomcat zip file, or did you have one already to use? Are there any output channels in the `OUTPUT` view for this server, and can you include any output it may include?

**Comment by robstryker** [comment]
Also are you able to edit the server and see any launch argumetns / vm arguments, or check a runnign process list to see what command it was launched with?

Finally, is the server reachable at localhost:8080 when you start the server? What about when it is stuck in `stopping` state?

**Comment by jackylo-hc** [comment]
@robstryker 
I cannot stop the server as well.
My case is:
- Window user
- I download Tomcat 9.0.88 from official website and put in my computer
- I change the server.xml to port 5000 as I cannot start in default 8005
- When in stopping state, I still can access localhost:8080
