### ISSUE TITLE
Felix framework adapters shows wrong label after restart

### ISSUE THREAD

**Issue by odockal** [redhat-developer/rsp-server-community#27]
1. Create Felix 6.0.3 server adapter
2. Start the adapter
3. ASSERT: Adapter is started
4. Invoke context menu item -> Restart in Run mode
5. ASSERT: Adapters stops and then goes back to started
6. Actually it stops and goes back but the label shows state stopped.

**Comment by odockal** [comment]
This opens an option to start adapter again which ends up in starting another process or failing due to one running (ie, for jetty adapters that fails to bind ip address on the same port)

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/600

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/600 closed

**Comment by odockal** [comment]
@robstryker Does this patch already got to the master branch? I was trying this patch and it did not work. Not sure if I got proper changes, can you also please try locally if you can reproduce this with the patch?

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server-community/pull/62/files

**Comment by robstryker** [comment]
Please try again with released version 0.23.7

Last updated | 9/17/2020, 10:54:17 AM

I released it again after seeing this bug. Please verify if possible.

**Comment by odockal** [comment]
@robstryker Now it works nicelly!. Thanks!
