### ISSUE TITLE
Community Server Connector not usable (stuck in weird state)

### ISSUE THREAD

**Issue by akaroml** [redhat-developer/rsp-server-community#31]
Here's what is listed in the server list:
![image](https://user-images.githubusercontent.com/16755094/85995269-a9e86e00-ba30-11ea-92e0-75de764740b0.png)

When I tried to start the server, the following error showed:
![image](https://user-images.githubusercontent.com/16755094/85995425-c97f9680-ba30-11ea-99ad-a2d136348d36.png)

I also tried to add a new server by downloading, but it never showed up in the server list. Instead, I saw this message in the output (stdout) channel:
![image](https://user-images.githubusercontent.com/16755094/86068161-32a2f080-baa9-11ea-8d8f-8c846297f646.png)

It seemed to be running but in the stderr output channel, there is an error:
![image](https://user-images.githubusercontent.com/16755094/86068175-3df61c00-baa9-11ea-833c-b26654473d50.png)

Could you help suggest how I could recover form this?

**Comment by robstryker** [comment]
I'll see what I can find out / try to replicate when I wake up. 

For now, can you give some info like what OS you're running? And if you can check the running process list, get the command that was run to launch the apache felix instance (with flags etc?)

**Comment by lstocchi** [comment]
@akaroml by looking at your logs it looks to me you are using vscode insiders, right? We never tested it with that version but we always used the stable vscode. So a quick solution could be to switch vscode until we have a fix for this.

**Comment by robstryker** [comment]
As for the illegal-reflective-things,  seems this is a warning common in apache felix depending on your java version.  See https://issues.apache.org/jira/browse/FELIX-5765

I'd say that is not a significant issue at this time (but annoying and confusing to a user, sure) and the real issue is why the UI isn't showing the change in rsp state.

**Comment by akaroml** [comment]
# Environment
Version: 1.47.0-insider
Commit: 04203498480e48be84d86f5763e126c7c5bf22e0
Date: 2020-06-30T09:01:06.154Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

# Running Java processes
`/Library/Java/JavaVirtualMachines/jdk-14.jdk/Contents/Home/bin/java -Drsp.server.port=9000 -Dorg.jboss.tools.rsp.id=redhat-community-server-connector -Dlogback.configurationFile=./conf/logback.xml -jar /Users/roml/.vscode-insiders/extensions/redhat.vscode-community-server-connector-0.22.10/server/bin/felix.jar`

# Results in Stable version
@lstocchi I tried using stable version and got this:
![image](https://user-images.githubusercontent.com/16755094/86198021-43c32e80-bb89-11ea-9866-98e9afc04850.png)
It's slightly different this time, status is `Stopped` instead of `Unknown`.
And the error log in output channel:
![image](https://user-images.githubusercontent.com/16755094/86197997-37d76c80-bb89-11ea-9c76-bbb99bbac95e.png)

While you take a further look, could you let me know if I can recover by something like cleaning cache files somewhere?

**Comment by lstocchi** [comment]
@akaroml to solve that issue just go to that folder `/Users/roml/.rsp/redhat-community-server-connector` and delete the file .lock

That file exists because if you launch an RSP twice with the same start args, it will have 2 different processes attempting to use the same data location. The two processes will clobber each other's edits routinely. To fix this issue we are using a .lock file to check if the workspace is already in use. In this case i think you have a dirty env as the server already started when using vscode-insiders. 

Let us know if it works with this hack. Thank you!!

**Comment by akaroml** [comment]
> @akaroml to solve that issue just go to that folder `/Users/roml/.rsp/redhat-community-server-connector` and delete the file .lock
> 
> That file exists because if you launch an RSP twice with the same start args, it will have 2 different processes attempting to use the same data location. The two processes will clobber each other's edits routinely. To fix this issue we are using a .lock file to check if the workspace is already in use. In this case i think you have a dirty env as the server already started when using vscode-insiders.
> 
> Let us know if it works with this hack. Thank you!!

It worked! Thanks.

Then I tried to see if it works in a new VS Code window (same stable version), and it did not work, the same error appeared.
Having a global lock seems to be causing the problem. Is this behavior as designed? I'm asking because it's very common for a user to have multiple VS Code windows at the same time.

**Comment by robstryker** [comment]
Sounds like we overlooked the usecase of multiple windows. I will provide a patch ASAP to be able to connect from a 2nd vscode window without launching a 2nd instance of the rsp process, simply connecting to the existing one. Luckily most of the infrastructure to do that already exists and we'll only need minor tweaks. 

I look forward to fixing this for you all.

**Comment by robstryker** [comment]
I'm submitting patches right now to rsp-server-community and vscode-server-connector to connect to an existing instance if one is running.  The lock file actually contains a port number. Until today we were checking if the lockfile existed and, if it did, gave up saying we couldn't launch a new instance. Instead we can now connect to the existing instance. 

However, these patches won't fix everything. There's a problem when you launch code, if you have 2 windows popping up at once. They will both fight to be the one that gets to launch the RSP depending on circumstance. In some cases, one will launch clearly first and the 2nd will recognize the first is already running adn simply connect to it. But in some instances, they will both try to launch and then the state will get all screwed up ;) 

There's another issue, as well. When we close vscode, we shutdown all rsps. If you have an rsp running, and two windows are connected to it, when you close one window it will shut down the rsp as well. So we'll need to fix that as well. We might even need to enhance API at the core rsp level as well. Right now when a client (vscode, intellij, whatever) exits, we tell the rsp to shut itself down. We may need to add a new API that basically says something like 'shut down if you have no clients remaining' and we can call that one on exit.

**Comment by imnotitguys** [comment]
> @akaroml to solve that issue just go to that folder `/Users/roml/.rsp/redhat-community-server-connector` and delete the file .lock
> 
> That file exists because if you launch an RSP twice with the same start args, it will have 2 different processes attempting to use the same data location. The two processes will clobber each other's edits routinely. To fix this issue we are using a .lock file to check if the workspace is already in use. In this case i think you have a dirty env as the server already started when using vscode-insiders.
> 
> Let us know if it works with this hack. Thank you!!

It works for me with this solution. Thank you @akaroml
