### ISSUE TITLE
Load custom configuration for Tomcat

### ISSUE THREAD

**Issue by alminisl** [redhat-developer/rsp-server-community#37]
Hello, 

Really like the extension! 

However I have a question, is it possible (since I don't see the option in the server config json) to change the path to a custom tomcat configuration ?

Edit: I've seen that this extensions https://github.com/redhat-developer/vscode-server-connector has an argument called `"wildfly.server.config.file"` something similar would be nice for Tomcat 

Thanks

**Comment by robstryker** [comment]
Not at this time, but that's a great enhancement idea. I'll leave the issue open so I can investigate it :D Shouldn't be too hard if all that changes is what command line args we pass in.

**Comment by robstryker** [comment]
Current solution is incorrect. Not even sure how to actually do this at the moment.

**Comment by alminisl** [comment]
@robstryker so this feature is a no go for now? :( 

I really would love it since I use a non default location for my config and I would gladly love the option like in Eclipse for example, to point to my configuration.

**Comment by robstryker** [comment]
@alminisl  I can try to add it back in, but my current solution was incorrect and I haven't figured out how to actually point to a custom configuration file. Do you know, for example, what flags need to be passed in to use a custom server.xml file? I was browsing tomcat docs nad the closest I found was a properties file, but not an actual server.xml file.

**Comment by robstryker** [comment]
Looking at the eclipse solution, I've discovered the following:

1) Server is launched with following flags
```
java -Dcatalina.base=/home/rob/apps/eclipse/workspaces/rsp_new/.metadata/.plugins/org.eclipse.wst.server.core/tmp0 -Dcatalina.home=/home/rob/apps/apache/tomcat/8.5.bak/apache-tomcat-8.5.56 -Dwtp.deploy=/home/rob/apps/eclipse/workspaces/rsp_new/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps -Djava.endorsed.dirs=/home/rob/apps/apache/tomcat/8.5.bak/apache-tomcat-8.5.56/endorsed -Dfile.encoding=UTF-8 -classpath /home/rob/apps/apache/tomcat/8.5.bak/apache-tomcat-8.5.56/bin/bootstrap.jar:/home/rob/apps/apache/tomcat/8.5.bak/apache-tomcat-8.5.56/bin/tomcat-juli.jar:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.fc30.x86_64/lib/tools.jar org.apache.catalina.startup.Bootstrap start
```

The important parts of that appear to be these two flags:
```
-Dcatalina.base=/home/rob/apps/eclipse/workspaces/rsp_new/.metadata/.plugins/org.eclipse.wst.server.core/tmp0 
-Dcatalina.home=/home/rob/apps/apache/tomcat/8.5.bak/apache-tomcat-8.5.56 
```
Looking at documentation, catalina.home appears to be where your main installation lives, whereas catalina.base is a copy of conf, logs, temp, webapps, work, etc. 

I do not expect our vscode extension to ever copy that much of an installation into a random hidden location on disk and pass in that configuration. Sorry, that's just not what I would want this specific tool to do on its own. However, if YOU wanted to do that on your own, and create your own catalina.base folder and pass in the flags for it, you can do it. You can just edit your server and pass those flags in via "args.vm.override.string" in the server editor. 

Problem is, right now that doesn't seem to be working ;) I can look into what's wrong with this specific part. 

But do you have any more input as to how you'd like this feature to work? Are you really looking for the tool to create a new base for you entirely? Or do you just want the ability to point to an existing base?

**Comment by robstryker** [comment]
Seems I forgot a step and it works for me :D 

Not only do you have to add the -Dcatalina.base flag into your vm args, you also need to change "args.vm.override.string" to true.

**Comment by alminisl** [comment]
> Seems I forgot a step and it works for me :D
> 
> Not only do you have to add the -Dcatalina.base flag into your vm args, you also need to change "args.vm.override.string" to true.
YES! 

`-Dcatalina.base=/home/rob/apps/eclipse/workspaces/rsp_new/.metadata/.plugins/org.eclipse.wst.server.core/tmp0 
-Dcatalina.home=/home/rob/apps/apache/tomcat/8.5.bak/apache-tomcat-8.5.56 `

this is the thing I need, at least the possiblity to somehow point tomcat to the config.
Can you please make a small "how to" guide? Did you add those arguments directly in the extension or the configs ? 

Thanks!

**Comment by robstryker** [comment]
No, I won't be adding these as default arguments because we won't be copying all the configuration files into their own folder like eclipse does. We don't want to take that responsibility. If a user wishes to make their own catalina base directory, they are free to do it by copying those files into a folder of their choice. Steps below:

1) Create a tomcat server adapter
2) manually create a folder on your filesystem with the catalina.policy, catalina.properties, context.xml, server.xml, tomcat-users.xml, and web.xml files. 
3) In vscode, right-click your tomcat server and select `edit server`
4) in the resulting editor, modify the following settings:
   a) change the args.override.boolean property to 'true' 
   b) change the args.vm.override.string property to '-Dcatalina.base=c:\path\to\folder\you\created'

**Comment by alminisl** [comment]
> No, I won't be adding these as default arguments because we won't be copying all the configuration files into their own folder like eclipse does. We don't want to take that responsibility. If a user wishes to make their own catalina base directory, they are free to do it by copying those files into a folder of their choice. Steps below:
> 
> 1. Create a tomcat server adapter
> 2. manually create a folder on your filesystem with the catalina.policy, catalina.properties, context.xml, server.xml, tomcat-users.xml, and web.xml files.
> 3. In vscode, right-click your tomcat server and select `edit server`
> 4. in the resulting editor, modify the following settings:
>    a) change the args.override.boolean property to 'true'
>    b) change the args.vm.override.string property to '-Dcatalina.base=c:\path\to\folder\you\created'

Thanks! Thats enough for me !

**Comment by robstryker** [comment]
Does the folder `D:\dev\.metadata\.plugins\org.eclipse.wst.server.core\tmp0` actually exist and does it have all the expected catalina files in it etc?

**Comment by alminisl** [comment]
> Does the folder `D:\dev\.metadata\.plugins\org.eclipse.wst.server.core\tmp0` actually exist and does it have all the expected catalina files in it etc?

Yes ? 
![image](https://user-images.githubusercontent.com/6343910/87652542-a3f2cc80-c754-11ea-848e-1faaf535aa0a.png)

![image](https://user-images.githubusercontent.com/6343910/87652573-ace39e00-c754-11ea-8e6b-7f256a0f747c.png)

The catalina files are however in the tmp0/conf

**Comment by robstryker** [comment]
I see the error now. You've added those flags to "args.program.override.string" instead of adding it to args.vm.override.string.  Please try moving those flags. 

But now I'm also wondering if my program args has an issue ;) I'll have to check that

**Comment by robstryker** [comment]
Just found a kind of critical bug in all the community adapters. Simple fix but your screenshots revealed it ;) 

Long story short, after the server is created, it's supposed to actually have values in args.program.override.string and args.vm.override.string.   All the generated values that we use to launch are supposed to be there for you to edit. If you try my suggestion above, right now, you'll be missing a huge number of critical flags etc. 

This was a pretty dumb mistake. I'm opening an issue for it now.

**Comment by alminisl** [comment]
> Just found a kind of critical bug in all the community adapters. Simple fix but your screenshots revealed it ;)
> 
> Long story short, after the server is created, it's supposed to actually have values in args.program.override.string and args.vm.override.string. All the generated values that we use to launch are supposed to be there for you to edit. If you try my suggestion above, right now, you'll be missing a huge number of critical flags etc.
> 
> This was a pretty dumb mistake. I'm opening an issue for it now.

Glad I could help 😄  Even tho accidentally 😄 

And its working like a charm now 😉 Thank you very much! From my side, this issue is resolved! 

Sorry if I bothered I'm new to the tomcat world 😅

**Comment by robstryker** [comment]
Thanks for the help!
