### ISSUE TITLE
Unable to Stop Tomcat 8.5 server in VSCode

### ISSUE THREAD

**Issue by rwankar** [redhat-developer/rsp-server-community#44]
I'm using the latest version 0.23.1 of the community-server with VSCode version 1.47.0

- I have set up a Tomcat server with "Server on disk" option
- And have set server.http.port to 8888

Steps to reproduce.
- Start the server from VS Code
- Click Stop on the connector. I get messages like the following and the application does not stop and the connector extension just shows "Stopping..". If I then click Terminate, the app still does not stop while the connector thinks the app has stopped and starting the app now shows "Bind exception address already in use" messages as the app has not yet stopped so the addresses are in use.

If I run CATALINA_HOME/bin/shutdown.sh from command line the app stops successfully.

```
WARNING: The web application [myapp] registered the JDBC driver [com.celoxis.framework.db.DriverProxy] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Jul 13, 2020 1:38:29 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [myapp] appears to have started a thread named [Log4j2-TF-5-Scheduled-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.7/jdk.internal.misc.Unsafe.park(Native Method)
```

**Comment by robstryker** [comment]
Hey @rwankar  

I'm not actually able to replicate this. My steps were as follows:
```
unzip apache-tomcat-8.5.56.zip 
cd apache-tomcat-8.5.56/conf
vi server.xml  # replace 8080 with 8090
```

In vscode, create new server, from disk, point to correct folder, give the server a name (tc85test). Server is created, so edit the server and change the field   "server.http.port": "8080"  to    "server.http.port": "8090"

Save the editor, start the server, notice proper output. Stop the server, also notice proper output.

**Comment by rwankar** [comment]
Hi @robstryker,

I think this more of an issue with our code where "bad" threads don't shutdown properly (If you Google "tomcat failed to stop threads") you'll come across a lot of stuff. In particular this one probably sheds more light. [https://github.com/opensourceBIM/BIMserver/issues/710]

What is surprising though is the same works fine when we call Tomcat's shutdown.sh from the command line and also via Eclipse. I just wanted to check if the way this plugin is trying to shutdown Tomcat has anything to do with it. For example, if there is a way to "force shutdown" all threads.

Thanks for looking in to this.

**Comment by robstryker** [comment]
So I've analyzed the shutdown command used when using shutdown.sh and the one used from the RSP extension. Methodology was to make a script to log 1000 calls to ps -ax | grep stop and redirect output to a file, then shutdown via extension or via shutdown.sh.  I took the commands actually being run (on my system at least) and compared them. 

The differences are as follows. Shutdown via RSP includes the flag 
-Djava.util.logging.config.file=/home/rob/apps/apache/tomcat/apache-tomcat-8.5.56/conf/logging.properties  which shutdown.sh does not include.   shutdown.sh includes the flag  -Dignore.endorsed.dirs=   (yes, thats right, empty) which rsp does not include. 

I would find it hard to believe these differences are material. All other flags are identical (though maybe in a different order? Should that affect anything?) including classpath, program args, etc. 

As for force-shutdown, the 'terminate' action is supposed to ask the RSP to kill the process it spawned, and this usually works IF the RSP is actually the one that spawned the process.  Sometimes, you may have a process already running in the background which you forgot about which can cause strange behavior... 

Not really sure where to go on this one considering what I've just looked into. No real leads here other than make sure there's no rogue processes in the background?

**Comment by rwankar** [comment]
So I created a sample app where you can see the issue even though there are no rogue threads.

Steps to reproduce
1. unzip the attached sample.zip
2. unzip the attached sample-server.zip file under ~/.rsp/redhat-community-server-connector/servers
3. Replace the path in the sample (servers file) to point to the location where you unzipped the sample.zip
4. Start VS Code and start the sample app
5. Confirm sample app running at localhost:8888/sample (You will see Hello World)
6. Stop the app from VSCode.

Environment
Java version is Amazon Corretto 11.0.7

VSCode Details
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

Observations.

1. Output in VSCode will show messages like...

SEVERE: Failed to initialize connector [Connector[HTTP/1.1-8888]]
org.apache.catalina.LifecycleException: Protocol handler initialization failed
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:995)

SEVERE: Failed to initialize connector [Connector[AJP/1.3-8009]]
org.apache.catalina.LifecycleException: Protocol handler initialization failed
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:995)

Jul 14, 2020 10:07:34 AM org.apache.catalina.core.StandardServer await
SEVERE: StandardServer.await: create[localhost:8005]: 
java.net.BindException: Address already in use (Bind failed)
	at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)

and towards the end..

INFO: Stopping service [Catalina]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.catalina.loader.WebappClassLoaderBase (file:/Users/ravi/Downloads/sample/lib/catalina.jar) to field java.io.ObjectStreamClass$Caches.localDescs
WARNING: Please consider reporting this to the maintainers of org.apache.catalina.loader.WebappClassLoaderBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jul 14, 2020 10:07:34 AM org.apache.catalina.core.ApplicationContext log
INFO: SessionListener: contextDestroyed()
Jul 14, 2020 10:07:34 AM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: contextDestroyed()
Jul 14, 2020 10:07:34 AM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-nio-8888"]
Jul 14, 2020 10:07:34 AM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-nio-8888"]
Jul 14, 2020 10:07:34 AM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["ajp-nio-8009"]
Jul 14, 2020 10:07:34 AM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["ajp-nio-8009"]

2. The connector will show "Stopping" but the app does not stop

3. From terminal check that the app is still running using ps -ef | grep java

[sample-server.zip](https://github.com/redhat-developer/rsp-server-community/files/4916598/sample-server.zip)
[sample.zip](https://github.com/redhat-developer/rsp-server-community/files/4916599/sample.zip)

**Comment by rwankar** [comment]
Hi @robstryker 

I hope you were able to see the issue with the samples I provided. Assume you are looking into it?

Regards,

**Comment by jeffmaury** [comment]
@robstryker is on PTO so I'm relaying him but I will be also PTO for 2 weeks starting Monday. @lstocchi will be following this issue.
I try to reproduce on Windows but I was not able to get it. I noticed that you are on MacOS and using Corretto and that the Corretto version you are using as a patch for MacOS, can you make sure you are using this version ?

**Comment by rwankar** [comment]
@jeffmaury , no issues. Was just wondering since there was no update.

I'm not sure what you mean by "using as a patch" but here is what I have done.

-  Installed Amazon Coretto 11 on MacOS.
- In settings.json I've added Coretto to "java.configuration.runtimes" 
- Set "java.home" in ~/.rsp/redhat-community-server-connector/servers/<server name> as below
"java.home" : "/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk"

Thanks

**Comment by jeffmaury** [comment]
If you go to https://github.com/corretto/corretto-11/releases you will notice two version regarding 11.0.7. I used 11.0.7.10.1 for my test by seems 11.0.7.10.1-1 has patches for MacOS only

**Comment by rwankar** [comment]
So I just updated to 11.0.8. OpenJDK Runtime Environment Corretto-11.0.8.10.1 (build 11.0.8+10-LTS). Still same issue.

**Comment by jeffmaury** [comment]
I looked at your server configuration file and it looks to me that you removed some generated values in the field: `args.vm.override.string`

**Comment by rwankar** [comment]
I didn't think so. Are you expecting something to be in there?

**Comment by jeffmaury** [comment]
Yes, here what I have when I created my server:
`
"args.vm.override.string": "-Djava.util.logging.config.file=c:\\apps\\tomcat\\sample/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dcatalina.base=c:\\apps\\tomcat\\sample -Dcatalina.home=c:\\apps\\tomcat\\sample -Djava.io.tmpdir=c:\\apps\\tomcat\\sample/temp",`

What's in your server file:

`"args.vm.override.string": "-Dceloxis.shutdown.port=8005 -Dceloxis.ajp.port=8009 -Dceloxis.http.port=8888 -Dceloxis.https.port=0",`

**Comment by lstocchi** [comment]
I tried it as well and i guess i'm having a different behavior. 
By trying your sample-server i have an issue similar to you, the server starts correctly but it doesn't stop (error logs below). It is stuck to `stopping` but i can terminate it (afaik you can't).

If i set args.override.boolean to false, rsp will reset the args to start the server and it works perfectly. If you run it this way (args.override.boolean to false) you have the same exact error log?

```
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version name:   Apache Tomcat/8.5.50
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built:          Dec 7 2019 19:19:46 UTC
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version number: 8.5.50.0
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name:               Linux
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Version:            5.6.13-100.fc30.x86_64
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Architecture:          amd64
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home:             /usr/local/java/jdk1.8.0_212/jre
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Version:           1.8.0_212-b10
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor:            Oracle Corporation
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE:         /home/luca/tmp/sample
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME:         /home/luca/tmp/sample
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dceloxis.shutdown.port=8012
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dceloxis.ajp.port=8009
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dceloxis.http.port=8888
Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dceloxis.https.port=0
Jul 24, 2020 1:57:02 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
Jul 24, 2020 1:57:02 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8888"]
Jul 24, 2020 1:57:02 PM org.apache.catalina.core.StandardService initInternal
SEVERE: Failed to initialize connector [Connector[HTTP/1.1-8888]]
org.apache.catalina.LifecycleException: Protocol handler initialization failed
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:995)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:552)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:848)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:639)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:303)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:221)
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1118)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:223)
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:581)
	at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:70)
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:993)
	... 12 more

Jul 24, 2020 1:57:02 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-nio-8009"]
Jul 24, 2020 1:57:02 PM org.apache.catalina.core.StandardService initInternal
SEVERE: Failed to initialize connector [Connector[AJP/1.3-8009]]
org.apache.catalina.LifecycleException: Protocol handler initialization failed
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:995)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardService.initInternal(StandardService.java:552)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:848)
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:639)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:303)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:221)
	at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1118)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:223)
	at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:581)
	at org.apache.catalina.connector.Connector.initInternal(Connector.java:993)
	... 12 more

Jul 24, 2020 1:57:02 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 496 ms
Jul 24, 2020 1:57:02 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Catalina]
Jul 24, 2020 1:57:03 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.5.50
Jul 24, 2020 1:57:03 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory [/home/luca/tmp/sample/webapps/host-manager]
Jul 24, 2020 1:57:03 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [/home/luca/tmp/sample/webapps/host-manager] has finished in [213] ms
Jul 24, 2020 1:57:03 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory [/home/luca/tmp/sample/webapps/examples]
Jul 24, 2020 1:57:03 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: contextInitialized()
Jul 24, 2020 1:57:03 PM org.apache.catalina.core.ApplicationContext log
INFO: SessionListener: contextInitialized()
Jul 24, 2020 1:57:03 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: attributeAdded('StockTicker', 'async.Stockticker@414dedc4')
Jul 24, 2020 1:57:03 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [/home/luca/tmp/sample/webapps/examples] has finished in [175] ms
Jul 24, 2020 1:57:03 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory [/home/luca/tmp/sample/webapps/manager]
Jul 24, 2020 1:57:03 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [/home/luca/tmp/sample/webapps/manager] has finished in [14] ms
Jul 24, 2020 1:57:03 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory [/home/luca/tmp/sample/webapps/docs]
Jul 24, 2020 1:57:03 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [/home/luca/tmp/sample/webapps/docs] has finished in [11] ms
Jul 24, 2020 1:57:03 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory [/home/luca/tmp/sample/webapps/ROOT]
Jul 24, 2020 1:57:03 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [/home/luca/tmp/sample/webapps/ROOT] has finished in [13] ms
Jul 24, 2020 1:57:03 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory [/home/luca/tmp/sample/webapps/sample]
Jul 24, 2020 1:57:03 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory [/home/luca/tmp/sample/webapps/sample] has finished in [18] ms
Jul 24, 2020 1:57:03 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 480 ms
Jul 24, 2020 1:57:03 PM org.apache.catalina.core.StandardServer await
SEVERE: StandardServer.await: create[localhost:8005]: 
java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at org.apache.catalina.core.StandardServer.await(StandardServer.java:421)
	at org.apache.catalina.startup.Catalina.await(Catalina.java:776)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:722)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)

Jul 24, 2020 1:57:03 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-nio-8888"]
Jul 24, 2020 1:57:03 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["ajp-nio-8009"]
Jul 24, 2020 1:57:03 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service [Catalina]
Jul 24, 2020 1:57:03 PM org.apache.catalina.core.ApplicationContext log
INFO: SessionListener: contextDestroyed()
Jul 24, 2020 1:57:03 PM org.apache.catalina.core.ApplicationContext log
INFO: ContextListener: contextDestroyed()
Jul 24, 2020 1:57:03 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-nio-8888"]
Jul 24, 2020 1:57:03 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-nio-8888"]
Jul 24, 2020 1:57:03 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["ajp-nio-8009"]
Jul 24, 2020 1:57:03 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["ajp-nio-8009"]

```

**Comment by rwankar** [comment]
@jeffmaury I regenerated the sample server file and got what you wrote but "args.override.boolean" is false. Now start/stop works fine.

But If you set "args.override.boolean": "true" you won't be able to Stop it. I think this is what @lstocchi is also noticing.

**Comment by jeffmaury** [comment]
Yes I was able to reproduce once I set `args.override.boolean` to `true`. My guess is that once you do that, as `args.program.override.string` is `start`, stopping the server will try to start it!!!!

**Comment by rwankar** [comment]
Is a fix in progress?

**Comment by lstocchi** [comment]
@rwankar actually no. I thought you found a solution and you were able to start/stop it ??? As @jeffmaury said @robstryker is PTO and we are in limited number atm. If there is an urgency we can fix this but if it works I would wait until Rob is back. Let me know.

**Comment by rwankar** [comment]
@lstocchi, since @jeffmaury said he was able to locate the issue I didn't try anything. It is not an urgent matter.

**Comment by robstryker2** [comment]
Back from PTO.  I'll try to look into this once I get set up again. 

As a quick test, though, I'd ask you to try the following.   Change your vm-args to include all of the original AND your additions.  As @jeffmaury  indicated, his attempt to stop has all of the flags required, and yours has only your app's custom flags.  Try to set that value to one that includes all of the default flags and your flags added to it, and see if that works? 

So for example, set args.override.boolean  to true and set args.vm.override.string  to the original default value PLUS your customizations?  Ex:

-Djava.util.logging.config.file=c:\\apps\\tomcat\\sample/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dcatalina.base=c:\\apps\\tomcat\\sample -Dcatalina.home=c:\\apps\\tomcat\\sample -Djava.io.tmpdir=c:\\apps\\tomcat\\sample/temp -Dceloxis.shutdown.port=8005 -Dceloxis.ajp.port=8009 -Dceloxis.http.port=8888 -Dceloxis.https.port=0


Let me know if that works?

**Comment by rwankar** [comment]
Hi @robstryker,

Thanks for taking the time to address this. I did make the change as suggested but it didn't help. As @jeffmaury observed that `args.program.override.string` is defaulted to `start` is the issue. Once I set it to blank, I am able to stop the server.

**Comment by robstryker** [comment]
Ok so the issue is more fundamental. We don't have separate args for overriding startup vs shutdown flags. The json values are assumed to affect only startup procedure but are also being used for shutdown when user overrides the values. 

Possible solutions are:
  1) Make overrides only valid for startup 
  2) Introduce new variables to override shutdown args and vm args

Got it.

**Comment by robstryker** [comment]
My first won't add new fields for users to customize. I'll just ensure that the values in the override only apply to startup, not shutdown. 

I'll open a new ticket to allow extra flags for overriding shutdown args and vm args.

**Comment by robstryker** [comment]
PR is here:  https://github.com/redhat-developer/rsp-server/pull/598

**Comment by robstryker** [comment]
Fixed / pushed
