### ISSUE TITLE
Server actions throws Unable to execute action Extension backend error - cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by odockal** [redhat-developer/rsp-server-community#49]
Happens on Apache tomcat, jetty and glassfih. I tried both started and stopped servers.

[Extension Host] Message=Sending request 'server/listServerActions - (53)'. data=Params: {    "id": "apache-tomcat-9.0.30",    "type": {        "id": "org.jboss.ide.eclipse.as.server.tomcat.90",        "visibleName": "Tomcat 9.x",        "description": "A server adapter capable of discovering and controlling a Tomcat 9.x runtime instance."    }}

[Extension Host] Message=Received response 'server/listServerActions - (53)' in 3ms. data=Result: {    "status": {        "severity": 4,        "plugin": "org.jboss.tools.rsp.server",        "code": 0,        "message": "Error loading actions: null",        "trace": "java.lang.NullPointerException\n\tat org.jboss.tools.rsp.server.generic.servertype.actions.GenericServerShowInBrowserActionHandler.getBaseUrl(GenericServerShowInBrowserActionHandler.java:46)\n\tat org.jboss.tools.rsp.server.generic.servertype.actions.AbstractShowInBrowserActionHandler.getInitialWorkflowInternal(AbstractShowInBrowserActionHandler.java:74)\n\tat org.jboss.tools.rsp.server.generic.servertype.actions.AbstractShowInBrowserActionHandler.getInitialWorkflow(AbstractShowInBrowserActionHandler.java:50)\n\tat org.jboss.tools.rsp.server.generic.servertype.GenericServerActionSupport.listServerActions(GenericServerActionSupport.java:43)\n\tat org.jboss.tools.rsp.server.generic.servertype.GenericServerBehavior.listServerActions(GenericServerBehavior.java:456)\n\tat org.jboss.tools.rsp.server.ServerManagementServerImpl.listServerActionsSync(ServerManagementServerImpl.java:818)\n\tat org.jboss.tools.rsp.server.ServerManagementServerImpl.lambda$34(ServerManagementServerImpl.java:807)\n\tat org.jboss.tools.rsp.server.ServerManagementServerImpl.lambda$36(ServerManagementServerImpl.java:906)\n\tat java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)\n\tat java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)\n\tat java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)\n\tat java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)\n\tat java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)\n\tat java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)\n"    }}

**Comment by robstryker** [comment]
This was fixed:  https://github.com/redhat-developer/rsp-server/commit/2d680f8558c1c11b1a63e32a7c058f03d48d00e5

**Comment by odockal** [comment]
@robstryker truly! Verified, thanks.
