### ISSUE TITLE
Karaf server does not start with java 11

### ISSUE THREAD

**Issue by odockal** [redhat-developer/rsp-server-community#50]
```Unable to execute action Extension backend error -```

**Comment by odockal** [comment]
[Extension Host] Message=Received response 'server/executeServerAction - (59)' in 1ms. data=Result: {    "status": {        "severity": 8,        "plugin": "unknown",        "code": 0,        "message": ""    },    "requestId": 0,    "items": []}

**Comment by robstryker2** [comment]
I am not able to replicate this issue.

**Comment by robstryker** [comment]
Anyone able to replicate this? @odockal ?

**Comment by odockal** [comment]
@robstryker Yes, still able to replicate. I cannot perform this action, and I get this output on the console when trying to call the action:
```
$ /usr/bin/ssh -p 8101 karaf@localhost
ssh: connect to host localhost port 8101: Connection refused
```

Maybe I need to have proper ssh client or something?

**Comment by robstryker** [comment]
Seems java9 plus, all the cmd line args are completely different. Ugh.
