### ISSUE TITLE
"vm.install.path" Server Parameter doesn't work

### ISSUE THREAD

**Issue by mulley001** [redhat-developer/rsp-server-community#53]
[redhat-developer/vscode-java](https://github.com/redhat-developer/vscode-java) updated and now requires JDK 11+ which creates an issue with the java.home setting. For example, I am working with Tomcat 8.5 and need to be able to run it with JDK 8, but since it utilizes java.home the server will always start with JDK 11+. I was looking at [redhat-developer/vscode-rsp-ui](https://github.com/redhat-developer/vscode-rsp-ui#global-server-parameters) and saw that they include a server parameter vm.install.path that allows for us to set the path for java home, but it seems that this extension does not utilize this parameter as even after setting the parameter the server still utilizes the JDK path set by java.home.

**Comment by lstocchi** [comment]
Sorry @mulley001 i completely missed it. We'll release a fix asap.

**Comment by robstryker** [comment]
This is fixed, but not yet released.
