### ISSUE TITLE
Verify changing Java home for different server adapters

### ISSUE THREAD

**Issue by odockal** [redhat-developer/rsp-server-community#55]
This is follow up for #54 where "vm.install.path" is going to be fixed for Tomcat server. Let's make sure we have this fix covered for all the server where configuration requires/allows this behavior.

**Comment by robstryker** [comment]
@odockal  I've manually verified that this works for tomcat and felix.

**Comment by odockal** [comment]
@robstryker And glassfish, karaf and jetty works as well too.
