### ISSUE TITLE
IBM Liberty server

### ISSUE THREAD

**Issue by tiagohumbs** [redhat-developer/rsp-server-community#66]
Is there any future plan for implementing IBM Liberty Server in this plugin?

Thanks!

**Comment by robstryker** [comment]
It's an idea. Not sure if it's on the "plan" yet. I'll need to investigate how it works a bit. I'll use this issue here to paste details as I discover them.

**Comment by robstryker** [comment]
Download page:  https://www.ibm.com/support/pages/node/6250961#asset/runtimes-wlp-javaee8

Creating a server:  https://www.ibm.com/support/knowledgecenter/en/SS7K4U_liberty/com.ibm.websphere.wlp.zseries.doc/ae/twlp_setup_new_server.html

**Comment by tiagohumbs** [comment]
Thanks. I will read the references and also try to understand how it works. Thank you very much for your support. =)

**Comment by robstryker** [comment]
Oh those messages were for me so I don't lose the info lol.  I doubt you'll learn anything new from there ;)
