### ISSUE TITLE
No way to set `java.home` independent of settings.json

### ISSUE THREAD

**Issue by jojojoy2k** [redhat-developer/rsp-server-community#70]
- My application runs on Java 1.8.
- Java language support on VSCode requires Java 11.
- When running tomcat through RSP, it picks up Java 11 setup in settings.json
Is there a way to start tomcat using a different java version instead of vscode's `java.home`?

**Comment by jeffmaury** [comment]
See https://github.com/redhat-developer/vscode-rsp-ui#extension-settings

**Comment by robstryker** [comment]
The setting that @jeffmaury  linked to only says what java to run the RSP server using. It doesn't decide what JVM to use when launching tomcat. When launching tomcat via the RSP, it will by default use whatever jvm the rsp-server is using. But they can actually all be different. 

If you right-click your tomcat server and select 'edit server', an editor should pop up. This is your tomcat's definition in the RSP, ie, how the RSP sees your tomcat server. If you add a setting "vm.install.path": "/path/to/your/jvm" you can customize the jvm used to launch each of your tomcat or other servers independently of each other. 

Hope this helps.
