### ISSUE TITLE
Tomcat 7 server doesn't work after updating to 0.23.12

### ISSUE THREAD

**Issue by PhilbyTheGreat** [redhat-developer/rsp-server-community#89]
After updating to version 0.23.12, tomcat 7 servers won't show for me in the servers window. If I downgrade to 0.23.10, the server reappears. Once I update to 0.23.12, it disappears. When I try to add the server again through create new servers (selecting no, use server on disk, then pointing to my tomcat directory), I get the message "Unable to create the server: Extension backend error - could not detect any server at d:\tomcat!". At the bottom of the error window, it says "Source: Remove Server Protocol UI (Extension)". Adding the server this way using 0.23.10 is successful.

If it makes any difference, this is on windows 10, trying to use tomcat 7.0.108. The version of the remote server protocol UI I have is 0.23.8.

**Comment by robstryker** [comment]
I'll give it a look. Thanks for the report.

**Comment by robstryker** [comment]
Replicated. Investigating whats going wrong.

**Comment by robstryker** [comment]
Made a release just now to the community extension. Thanks for pointing out this bug.
